dimensions: 2

num_tests: 10
num_particles: 25
max_iterations: 150

initial_inertia_weight: 0.72984
inertia_mode: 1
# 1 - stała
# 2 - zależna od czasu
# 3 - zależna od wartości rozwiązania

c1: 2.05
c2: 2.05

fun: 6
# 1 - wielomianowa:   f(x) =  0       x = (0, 0)
# 2 - booth:          f(x) =  0       x = (1, 3)
# 3 - rosenbrock:     f(x) =  0       x = (0, 0)
# 4 - ackley:         f(x) = -1.8013  x = (2.20, 1.57)
# 5 - michalewicz:    f(x) =  0       x = (0, 0)
# 6 - holder_table:   f(x) = -19.2085 x = ( 8.05502,  9.66459),
#                                     x = (-8.05502,  9.66459),
#                                     x = ( 8.05502, -9.66459),
#                                     x = (-8.05502, -9.66459)

draw_online: True
draw_result: False
